export enum QUERY_KEY {
  GET_ALL_DOCTORS = "GET_ALL_DOCTORS",
  GET_DOCTOR = "GET_DOCTOR",
  GET_PATIENT = "GET_PATIENT",
  GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS",
  GET_APPOINTMENT = "GET_APPOINTMENT",
  GET_ALL_SHIFTS = "GET_ALL_SHIFTS",
  DEPARTMENTS = "DEPARTMENTS",
}
